package com.supermarket.dataobject;

public class item_InfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.item_Code
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.item_Categroy
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemCategroy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.item_Price
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private Long itemPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.item_Id
     *
     * @return the value of item_info.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.item_Id
     *
     * @param itemId the value for item_info.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.item_Name
     *
     * @return the value of item_info.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.item_Name
     *
     * @param itemName the value for item_info.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.item_Code
     *
     * @return the value of item_info.item_Code
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.item_Code
     *
     * @param itemCode the value for item_info.item_Code
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.item_Categroy
     *
     * @return the value of item_info.item_Categroy
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemCategroy() {
        return itemCategroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.item_Categroy
     *
     * @param itemCategroy the value for item_info.item_Categroy
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemCategroy(String itemCategroy) {
        this.itemCategroy = itemCategroy == null ? null : itemCategroy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.item_Price
     *
     * @return the value of item_info.item_Price
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public Long getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.item_Price
     *
     * @param itemPrice the value for item_info.item_Price
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemPrice(Long itemPrice) {
        this.itemPrice = itemPrice;
    }
}