package com.supermarket.dataobject;

public class purchase_tableDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_table.purchase_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String purchaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_table.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_table.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_table.purchase_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private Integer purchaseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_table.purchase_Price
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private Long purchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_table.sum
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private Long sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_table.purchaser_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String purchaserNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_table.purchase_Id
     *
     * @return the value of purchase_table.purchase_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_table.purchase_Id
     *
     * @param purchaseId the value for purchase_table.purchase_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setPurchaseId(String purchaseId) {
        this.purchaseId = purchaseId == null ? null : purchaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_table.item_Id
     *
     * @return the value of purchase_table.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_table.item_Id
     *
     * @param itemId the value for purchase_table.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_table.item_Name
     *
     * @return the value of purchase_table.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_table.item_Name
     *
     * @param itemName the value for purchase_table.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_table.purchase_number
     *
     * @return the value of purchase_table.purchase_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public Integer getPurchaseNumber() {
        return purchaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_table.purchase_number
     *
     * @param purchaseNumber the value for purchase_table.purchase_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setPurchaseNumber(Integer purchaseNumber) {
        this.purchaseNumber = purchaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_table.purchase_Price
     *
     * @return the value of purchase_table.purchase_Price
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public Long getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_table.purchase_Price
     *
     * @param purchasePrice the value for purchase_table.purchase_Price
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setPurchasePrice(Long purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_table.sum
     *
     * @return the value of purchase_table.sum
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public Long getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_table.sum
     *
     * @param sum the value for purchase_table.sum
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setSum(Long sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_table.purchaser_number
     *
     * @return the value of purchase_table.purchaser_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getPurchaserNumber() {
        return purchaserNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_table.purchaser_number
     *
     * @param purchaserNumber the value for purchase_table.purchaser_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setPurchaserNumber(String purchaserNumber) {
        this.purchaserNumber = purchaserNumber == null ? null : purchaserNumber.trim();
    }
}