package com.supermarket.dataobject;

import java.util.Date;

public class storagesDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storages.storage_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String storageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storages.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storages.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storages.storage_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private Integer storageNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storages.storage_Date
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    private Date storageDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storages.storage_Id
     *
     * @return the value of storages.storage_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storages.storage_Id
     *
     * @param storageId the value for storages.storage_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setStorageId(String storageId) {
        this.storageId = storageId == null ? null : storageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storages.item_Id
     *
     * @return the value of storages.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storages.item_Id
     *
     * @param itemId the value for storages.item_Id
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storages.item_Name
     *
     * @return the value of storages.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storages.item_Name
     *
     * @param itemName the value for storages.item_Name
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storages.storage_number
     *
     * @return the value of storages.storage_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public Integer getStorageNumber() {
        return storageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storages.storage_number
     *
     * @param storageNumber the value for storages.storage_number
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setStorageNumber(Integer storageNumber) {
        this.storageNumber = storageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storages.storage_Date
     *
     * @return the value of storages.storage_Date
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public Date getStorageDate() {
        return storageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storages.storage_Date
     *
     * @param storageDate the value for storages.storage_Date
     *
     * @mbg.generated Sat Dec 07 21:32:53 CST 2019
     */
    public void setStorageDate(Date storageDate) {
        this.storageDate = storageDate;
    }
}